# Generated by Django 3.1.3 on 2021-04-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='description',
            new_name='Solution',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='issue',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mfg_date',
        ),
    ]
